//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionTreeWriter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DecisionTreeWriter.Resources.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addLeftNodeToolStripMenuItem.
        /// </summary>
        internal static string AddLeftNode {
            get {
                return ResourceManager.GetString("AddLeftNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addRightNodeToolStripMenuItem.
        /// </summary>
        internal static string AddRightNode {
            get {
                return ResourceManager.GetString("AddRightNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addRootToolStripMenuItem.
        /// </summary>
        internal static string AddRoot {
            get {
                return ResourceManager.GetString("AddRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a root first to begin a decision tree.
        /// </summary>
        internal static string AddRootMessage {
            get {
                return ResourceManager.GetString("AddRootMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addSubTreeToolStripMenuItem.
        /// </summary>
        internal static string AddSubTree {
            get {
                return ResourceManager.GetString("AddSubTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a node name before adding child nodes..
        /// </summary>
        internal static string EnterNodeNameMessage {
            get {
                return ResourceManager.GetString("EnterNodeNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the root before adding child nodes..
        /// </summary>
        internal static string EnterRootNameMessage {
            get {
                return ResourceManager.GetString("EnterRootNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This decision tree has already a root. Add a node or subtree..
        /// </summary>
        internal static string TreeHasRootMessage {
            get {
                return ResourceManager.GetString("TreeHasRootMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numeric value must be entered for this field.
        /// </summary>
        internal static string ValueIsNotNumericMessage {
            get {
                return ResourceManager.GetString("ValueIsNotNumericMessage", resourceCulture);
            }
        }
    }
}
